// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFcPYZmnCgZO-pGJmqUPfHYv-30OLLwE',
    appId: '1:755571879517:web:6053e7d9771004d41427b4',
    messagingSenderId: '755571879517',
    projectId: 'nfunayo',
    authDomain: 'nfunayo.firebaseapp.com',
    storageBucket: 'nfunayo.firebasestorage.app',
    measurementId: 'G-KG79HCGS1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrrMxNvnVSrX2phV6nfXH_guQ2ZI7r3Fw',
    appId: '1:755571879517:android:fb2c07fa74d8ed4b1427b4',
    messagingSenderId: '755571879517',
    projectId: 'nfunayo',
    storageBucket: 'nfunayo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ6deFXe4TGoVI8zc5Zsqlz_0ogLHWdR4',
    appId: '1:755571879517:ios:06a180f21c5404361427b4',
    messagingSenderId: '755571879517',
    projectId: 'nfunayo',
    storageBucket: 'nfunayo.firebasestorage.app',
    androidClientId: '755571879517-64mgbqnmaq60bcmqhsdmd7tu0fdagaf0.apps.googleusercontent.com',
    iosClientId: '755571879517-7umnqefol7ad7bcearbo2hbp7i7r1ec7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfunayoMini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ6deFXe4TGoVI8zc5Zsqlz_0ogLHWdR4',
    appId: '1:755571879517:ios:06a180f21c5404361427b4',
    messagingSenderId: '755571879517',
    projectId: 'nfunayo',
    storageBucket: 'nfunayo.firebasestorage.app',
    androidClientId: '755571879517-64mgbqnmaq60bcmqhsdmd7tu0fdagaf0.apps.googleusercontent.com',
    iosClientId: '755571879517-7umnqefol7ad7bcearbo2hbp7i7r1ec7.apps.googleusercontent.com',
    iosBundleId: 'com.example.nfunayoMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-WqIg7Pqf700GNsZP7Drgwzr5ZX59TC8',
    appId: '1:755571879517:web:eb584212bbee0db21427b4',
    messagingSenderId: '755571879517',
    projectId: 'nfunayo',
    authDomain: 'nfunayo.firebaseapp.com',
    storageBucket: 'nfunayo.firebasestorage.app',
    measurementId: 'G-4BJJ81P6EY',
  );
}
